# Generated by Django 6.0.6 on 2026-07-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('tubewells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tubewell',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tubewells.tubewell'),
            preserve_default=False,
        ),
    ]
