# Generated by Django 6.0.6 on 2026-07-02 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tubewells', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_self_use', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('rate_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed')], default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tubewell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='tubewells.tubewell')),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
