# Generated by Django 6.0.6 on 2026-07-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
