# Generated by Django 6.0.6 on 2026-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='textbee_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='textbee_device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
