# Generated by Django 6.0.6 on 2026-07-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_textbee_api_key_user_textbee_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='textbee_api_key',
            new_name='fast2sms_api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='textbee_device_id',
        ),
    ]
