# Generated by Django 6.0.6 on 2026-07-02 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tubewell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='tubewells', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedRenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_renters', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(limit_choices_to={'role': 'renter'}, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_by_owners', to=settings.AUTH_USER_MODEL)),
                ('tubewell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_renters', to='tubewells.tubewell')),
            ],
            options={
                'unique_together': {('owner', 'renter', 'tubewell')},
            },
        ),
    ]
