# Generated by Django 6.0.6 on 2026-07-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubewells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubewell',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
