# Generated by Django 6.0.6 on 2026-07-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubewells', '0002_tubewell_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedrenter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
